# A docker-compose file for testing the App in docker and the local environment:
version: "3.7"

services:
  headersv:
    image: headersv-app
    build:
      context: .
    volumes:
      - headersv-data:/tmp/jcl
    environment:
        #bsv-mainnet | bsv-testnet | bsv-stnnet | bsv-regtest
      - SPRING_PROFILES_ACTIVE=bsv-mainnet

        #HeaderSV Application Configuration - Other properties can be found in src/main/resources/application-bsv-xxx.yml
#      - HEADERSV_NETWORK_MINPEERS=15
#      - HEADERSV_NETWORK_MAXPEERS=25
#      - HEADERSV_NETWORK_PEERS=127.0.0.1
#      - HEADERSV_NETWORK_PORT:18444
#      - HEADERSV_NETWORK_DISCOVERYENABLED=false
      - _JAVA_OPTIONS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=25 -Dlogging.level.ROOT=INFO
    ports:
      - "8001:8080"

volumes:
  headersv-data:
    external: false
