# Application Configuration:
headersv:
  # Listener Configuration params:
  network:
    networkId: "stnnet"
    minPeers: 5
    maxPeers: 10
    initialConnections:

  sync:
    headersToIgnore:

  storage:
    pruning:
      fork:
        enabled: false
        pruneAfterConfirmations: 7
      orphan:
        enabled: false
        pruneAfterInterval: 600