# Application Configuration:
headersv:

  general:
    headersToIgnore:

  network:
    networkId: "testnet"
    shareP2P: "no"
    minPeers: 2
    maxPeers: 10
    initialConnections:

  storage:
    pruning:
      fork:
        enabled: false
        pruneAfterConfirmations: 7
      orphan:
        enabled: false
        pruneAfterInterval: 600