# Application Configuration:
headersv:

  general:
    headersToIgnore:
    invBroadcastEnabled: true
    sendHeadersEnabled: true
  network:
    networkId: "stnnet"
    shareP2P: "no"
    minPeers: 5
    maxPeers: 10
    initialConnections:
    genesisHeaderHex:

  storage:
    pruning:
      fork:
        enabled: false
        pruneAfterConfirmations: 7
      orphan:
        enabled: false
        pruneAfterInterval: 600